#!/bin/sh

mkdir -p "$1/api" "$1/web"

cp config/apache/server.conf "$1/server.conf"

echo 'API' > "$1/api/index.php"
echo 'WEB' > "$1/web/index.html"

cat > "$1/install" << EOF
#!/bin/sh
sudo apt-get update
sudo apt-get install apache2 libapache2-mod-php8.1 -y

sudo rm -rf /var/www/api
sudo rm -rf /var/www/web

sudo mkdir -p /var/www/api
sudo mkdir -p /var/www/web

sudo mkdir -p /var/www/ssl

sudo openssl req -x509 -nodes -days 1095 -newkey rsa:2048 -subj "/C=US/ST=State/L=City/O=Company/OU=Org/CN=localhost" -out /var/www/ssl/server.crt -keyout /var/www/ssl/server.key

sudo cp "$1/server.conf" /etc/apache2/sites-available/server.conf

sudo systemctl stop apache2

sudo a2dismod php8.1 mpm_event
sudo a2enmod rewrite ssl php8.1 || exit 1
sudo a2ensite server.conf

sudo apachectl configtest

sudo cp "$1/api"/* /var/www/api/
sudo cp "$1/web"/* /var/www/web/

sudo systemctl enable apache2
if ! sudo service apache2 start; then
	echo "[$1] ERROR:"
	journalctl -u apache2.service -n 50 --no-pager
	exit 1
fi

sudo systemctl status apache2 --no-pager -l
echo "[$1] INFO: done"
EOF
