#!/bin/sh

CONFIG='/var/www/api/config.php'
tmp_php="tmp.php"

if [ ! -f "$CONFIG" ] || [ -n "$PHP_PASS" ] || [ -n "$JWT_KEY" ]; then
	if [ -z "$PHP_PASS" ]; then
		echo 'ERROR: PHP_PASS not provided'
		exit 1
	fi

	if [ -z "$JWT_KEY" ]; then
		echo 'ERROR: JWT_KEY not provided'
		exit 1
	fi

	cp "config/php/config.php" "$tmp_php"
	sed -i "s;\${PHP_PASS};$PHP_PASS;g" "$tmp_php"
	sed -i "s;\${JWT_KEY};$JWT_KEY;g" "$tmp_php"
else
	sudo cp "$CONFIG" "$tmp_php"
	echo "INFO: Leaving old config"
fi

sudo rm -rf /var/www/api/*
sudo cp -r src/api/* /var/www/api/

sudo cp "$tmp_php" "$CONFIG"
sudo rm "$tmp_php"
