#!/bin/sh

if [ -z "$ADMIN_EMAIL" ]; then
        echo 'ERROR: ADMIN_EMAIL not provided'
        exit 1
fi

if [ -z "$ADMIN_USER" ]; then
        echo 'ERROR: ADMIN_USER not provided'
        exit 1
fi

if [ -z "$ADMIN_PASS" ]; then
        echo 'ERROR: ADMIN_PASS not provided'
        exit 1
fi

tmp_sql="tmp.sql"
cp "config/mysql/create.sql" "$tmp_sql"
sed -i "s;\${ADMIN_EMAIL};$ADMIN_EMAIL;g" "$tmp_sql"
sed -i "s;\${ADMIN_USER};$ADMIN_USER;g" "$tmp_sql"
sed -i "s;\${ADMIN_PASS};$ADMIN_PASS;g" "$tmp_sql"

sudo cat "$tmp_sql" | sudo mysql
rm "$tmp_sql"
