#!/bin/sh

CONFIG="$1/secure.sql"

if [ ! -f "$CONFIG" ] || [ -n "$PHP_PASS" ]; then
	if [ -z "$PHP_PASS" ]; then
		echo "[$1] ERROR: PHP_PASS not provided"
		exit 1
	fi

	cp config/mysql/secure.sql "$CONFIG"
	sed -i "s;\${PHP_PASS};$PHP_PASS;g" "$CONFIG"

else
	echo "[$1] INFO: Leaving old config"
fi

cat > "$1/install" << EOF
#!/bin/sh
sudo apt-get update
sudo apt-get install mysql-server -y
sudo systemctl enable mysql
sudo systemctl start mysql
sudo systemctl status mysql --no-pager -l
sudo cat "$CONFIG" | sudo mysql
echo "[$1] INFO: done"
EOF
