#!/bin/sh

mkdir -p "$1/api"

echo '<?php phpinfo();' > "$1/api/index.php"

cat > "$1/install" << EOF
#!/bin/sh
sudo apt-get update
sudo apt-get install php8.1 php-mysqli -y
sudo cp "$1/api"/* /var/www/api/
sudo systemctl restart apache2.service
echo "[$1] INFO: done"
EOF
