#!/bin/sh

ISO_NAME="ubuntu-22.04.5-live-server-amd64.iso"
ISO_URL="https://releases.ubuntu.com/22.04.5/$ISO_NAME"

CD=$(pwd)
TMP="$CD/tmp"
AUTOINSTALL="$TMP/autoinstall"
ISO="$AUTOINSTALL/$ISO_NAME"

ISO_FILES="$AUTOINSTALL/iso"
BOOT_DIR="$AUTOINSTALL/BOOT"

mkdir -p "$AUTOINSTALL"

sudo apt-get install xorriso whois -y

if [ ! -d "$ISO_FILES" ]; then
	if [ ! -f "$ISO" ]; then
		wget -O "$ISO" "$ISO_URL"
	fi

	sudo apt-get install p7zip-full -y
	mkdir -p "$ISO_FILES"
	7z -y x "$ISO" -o"$ISO_FILES"

	if [ -d "$BOOT_DIR" ]; then
		rm -r "$BOOT_DIR"
	fi
	mv "$ISO_FILES/[BOOT]" "$BOOT_DIR"
fi

GRUB_CFG="$ISO_FILES/boot/grub/grub.cfg"
# Don't request user confirmation, set source directory
sed -i 's/linux	\/casper\/vmlinuz  ---/linux	\/casper\/vmlinuz autoinstall ds=nocloud\\;s=\/cdrom\/server\/ ---/g' "$GRUB_CFG"
# Show prompt only for 1 second before autoinstall
sed -i 's/timeout=30/timeout=1/g' "$GRUB_CFG"

create_ssh() {
	SSH_KEY_PATH="$1"
	if [ -f "$SSH_KEY_PATH" ]; then
		rm "$SSH_KEY_PATH" "$SSH_KEY_PATH".pub
	fi
	ssh-keygen -t rsa -b 4096 -C "" -f "$SSH_KEY_PATH" -N "" -q
	cat "$SSH_KEY_PATH".pub
}

mkdir -p "$TMP/vm"
ROOT_SSH_KEY=$(create_ssh "$TMP/vm/root_rsa")
USER_SSH_KEY=$(create_ssh "$TMP/vm/user_rsa")

mkdir -p "$ISO_FILES/server"
touch "$ISO_FILES/server/meta-data"
# https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html
# mkpasswd --method=SHA-512 server
USERDATA="$ISO_FILES/server/user-data"
cp "config/vm/user-data" "$USERDATA"
sed -i "s;\${ROOT_SSH_KEY};$ROOT_SSH_KEY;g" "$USERDATA"
sed -i "s;\${USER_SSH_KEY};$USER_SSH_KEY;g" "$USERDATA"

cd "$ISO_FILES" || exit
xorriso -as mkisofs -r \
        -V 'Ubuntu 22.04 LTS AUTO (EFIBIOS)' \
        -o "$TMP/server.iso" \
        --grub2-mbr "$BOOT_DIR/1-Boot-NoEmul.img" \
        -partition_offset 16 \
        --mbr-force-bootable \
        -append_partition 2 28732ac11ff8d211ba4b00a0c93ec93b "$BOOT_DIR/2-Boot-NoEmul.img" \
        -appended_part_as_gpt \
        -iso_mbr_part_type a2a0d0ebe5b9334487c068b6b72699c7 \
        -c '/boot.catalog' \
        -b '/boot/grub/i386-pc/eltorito.img' \
        -no-emul-boot -boot-load-size 4 -boot-info-table --grub2-boot-info \
        -eltorito-alt-boot \
        -e '--interval:appended_partition_2:::' \
        -no-emul-boot \
        .
cd "$CD" || exit
