#!/bin/sh

CD=$(pwd)
TMP="$CD/tmp"
QCOW="$TMP/vm/disk.qcow"
TMP_QCOW="$TMP/vm/tmp.qcow"

cp "$QCOW" "$TMP_QCOW"

qemu-system-x86_64 -enable-kvm -nographic -drive file="$TMP_QCOW",format=qcow2 -m 2048 -net nic -net user,hostfwd=tcp::2222-:22,hostfwd=tcp::8080-:80 &

while :
do
	timeout 5 ./scripts/vm/user_ssh :
	res="$?"
	[ "$res" -eq "0" ] && return
	sleep 1
done
