#!/bin/sh

HOSTNAME="[localhost]:2222"
KNOWN_HOSTS="tmp/known_hosts"

mkdir -p tmp
touch "$KNOWN_HOSTS"
chmod 400 "tmp/vm/root_rsa"
chmod 400 "tmp/vm/user_rsa"

if [ -n "$(ssh-keygen -f "$KNOWN_HOSTS" -F "$HOSTNAME")" ]; then
	ssh-keygen -f "$KNOWN_HOSTS" -R "$HOSTNAME" -q
fi

./scripts/vm/start_qemu

start_time=$(date +%s)
i=0
while :
do
	current_time=$(date +%s)
	elapsed_time=$((current_time - start_time))

	printf "Time: %02d:%02d:%02d\n" \
		$((elapsed_time / 3600)) \
		$(( (elapsed_time % 3600) / 60 )) \
		$((elapsed_time % 60))

	ssh user_ssh@localhost -i tmp/vm/user_rsa -o UserKnownHostsFile=tmp/known_hosts -o StrictHostKeyChecking=no -o ConnectTimeout=1 -q -p 2222 ":" && break

	sleep 4
	i=$((i+1))

	if [ "$i" = "24" ]; then
		echo "Timeout"
		break
	fi
done

echo "Active VM connections:"
sudo netstat -tulpn | grep "qemu"

echo "Known Hosts:"
cat "$KNOWN_HOSTS"
