#!/bin/sh

php_pass=$1
jwt=$2

cp -r api /var/www
cp -r web /var/www

echo "localhost:php:$php_pass:3306" > /home/.mysql
echo "$jwt" > /home/.jwt

mysql -e "
DROP USER IF EXISTS 'php'@'localhost';
CREATE USER 'php'@'localhost' IDENTIFIED BY '$php_pass';
GRANT SELECT, UPDATE, INSERT, DELETE ON user.* TO 'php'@'localhost';
GRANT SELECT, UPDATE, INSERT, DELETE ON quiz.* TO 'php'@'localhost';
"

mysql < ./config/db.sql
mysql < ./config/test.sql
