#!/bin/sh

php_pass=$1
jwt=$2
email=$3
email_pass=$4

apt install apache2 php libapache2-mod-php8.1 mariadb-server php-mysqli sendmail mailutils -y
echo "\n--------------------APACHE----------------------\n"
apache2 -v
echo "\n----------------------PHP-----------------------\n"
php -v
echo "\n--------------------MARIADB---------------------\n"
mariadb -V
echo "\n------------------------------------------------\n"

cp -r api /var/www
cp -r web /var/www

a2enmod rewrite
a2enmod php8.1
cp ./config/000-default.conf /etc/apache2/sites-available
systemctl stop apache2
systemctl start apache2

echo "localhost:php:$php_pass:quiz:3306" > /home/.mysql
echo "$jwt" > /home/.jwt

mysql -e "
DROP USER IF EXISTS 'php'@'localhost';
CREATE USER 'php'@'localhost' IDENTIFIED BY '$php_pass';
GRANT SELECT, UPDATE, INSERT, DELETE ON quiz.* TO 'php'@'localhost';
"

mysql < ./config/db.sql
mysql < ./config/test.sql

sed -i "$(($(wc -l < /etc/mail/sendmail.mc)-3))i\define(\`SMART_HOST', \`smtp.gmail.com')dnl\ndefine(\`confAUTH_MECHANISMS', \`EXTERNAL GSSAPI DIGEST-MD5 CRAM-MD5 LOGIN PLAIN')dnl\nFEATURE(\`authinfo',\`hash -o /etc/mail/authinfo.db')dnl\ndnl" /etc/mail/sendmail.mc

echo "AuthInfo:smtp.gmail.com \"U:$email\" \"P:$email_pass\" \"M:PLAIN\"" > /etc/mail/authinfo
makemap hash /etc/mail/authinfo < /etc/mail/authinfo
make -C /etc/mail
systemctl enable sendmail.service
systemctl stop sendmail.service
systemctl start sendmail.service

