#!/bin/sh

apt install apache2 php libapache2-mod-php8.1 -y
echo "\n---------------------APACHE---------------------\n"
apache2 -v
echo "\n----------------------PHP-----------------------\n"
php -v
echo "\n------------------------------------------------\n"

cp -r api /var/www
cp -r web /var/www

a2enmod rewrite
a2enmod php8.1
cp ./config/000-default.conf /etc/apache2/sites-available
systemctl stop apache2
systemctl start apache2

