name: build
run-name: build-linux

on:
  push:
    branches: [ "main" ]
    paths:
      - 'config/**'
      - 'scripts/**'
      - 'src/**'
      - 'tests/**'
      - '!**/*.md'

  pull_request:
    branches: [ "main" ]
    paths:
      - 'config/**'
      - 'scripts/**'
      - 'src/**'
      - 'tests/**'
      - '!**/*.md'

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        run: sudo ./scripts/prepare

      - name: Build
        run: ./scripts/build

      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build
