name: Create OS Image

on:
  push:
    paths:
    - 'config/vm/user-data'

  workflow_dispatch:

jobs:
  create_os_image:
    name: Create OS Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: tmp/autoinstall
          key: ${{ runner.os }}-autoinstall-cache

      - name: Create OS Image
        run: ./scripts/vm/create_os_image

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: |
            ./tmp/vm/
            ./tmp/server.iso

      - name: Create VM
        uses: martis99/trigger-workflow@main
        with:
          workflow: create-vm
