name: Create autoinstall

on:
  push:
    paths:
    - 'config/vm/user-data'

  workflow_dispatch:

jobs:
  create_autoinstall:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: tmp/autoinstall
          key: ${{ runner.os }}-autoinstall-cache

      - name: Create autoinstall
        run: ./scripts/vm/create_autoinstall

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: autoinstall
          path: |
            ./tmp/vm/
            ./tmp/server.iso

      - name: Trigger VM
        uses: martis99/trigger-workflow@main
        with:
          workflow: create-qemu
