name: Create VM

on:
  workflow_dispatch:

jobs:
  create_vm:
    name: Create VM
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download OS Image
        uses: martis99/download-artifact@v1
        with:
          workflow: create-os-image
          artifact: image
          dir: tmp

      - name: Create VM
        run: ./scripts/vm/create

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vm
          path: ./tmp/vm

      - name: Trigger install tests
        uses: martis99/trigger-workflow@main
        with:
          workflow: test-install
