name: test
run-name: test-linux-web

on:
  workflow_run:
    workflows: [build]
    types: [completed]

  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: sudo ./scripts/install prod ${{secrets.EMAIL}} ${{secrets.EMAIL_PASS}} ${{secrets.ROOT_PASS}} ${{secrets.ADMIN_PASS}} ${{secrets.BACKUP_PASS}} ${{secrets.RESTORE_PASS}} ${{secrets.PHP_PASS}} ${{secrets.EMAIL_STATUS}}

      - name: Download
        uses: actions/download-artifact@v4
        with:
          github-token: ${{secrets.PAT}}
          run-id: ${{github.event.workflow_run.id}}
          name: build
          path: ./build

      - name: Deploy
        run: /scripts/deploy

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./web/package-lock.json

      - name: Run Tests
        working-directory: ./web/
        run: |
          npm ci
          npm run build --if-present
          npm test
