name: Test DB

on:
  workflow_dispatch:

jobs:
  test_db:
    name: Test DB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download VM
        uses: martis99/download-artifact@v1
        with:
          workflow: create-vm
          artifact: vm
          dir: tmp/vm

      - name: Start VM
        run: ./scripts/vm/start

      - name: Install DB
        run: ./scripts/install/db vm

      - name: Test DB
        run: ./scripts/install/test_db vm
