name: Test SSH

on:
  workflow_dispatch:

jobs:
  test_ssh:
    name: Test SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download VM
        uses: martis99/download-artifact@v1
        with:
          workflow: create-vm
          artifact: vm
          dir: tmp/vm

      - name: Start VM
        run: ./scripts/vm/start

      - name: Test ssh
        run: ./scripts/vm/test_ssh
